apiVersion: v2
name: kubectl-bot
description: A Kubernetes Telegram Bot that provides secure, RBAC-controlled access to Kubernetes cluster operations via Telegram
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/reloadlife/kbot
sources:
  - https://github.com/reloadlife/kbot
maintainers:
  - name: reloadlife
    url: https://github.com/reloadlife
keywords:
  - kubernetes
  - telegram
  - bot
  - kubectl
  - rbac
  - automation
icon: https://telegram.org/img/t_logo.png
